// Generated by Wrangler by running `wrangler types`

interface Env {
    NODE_ENV: string
    OAUTH_KV: KVNamespace
    KINDE_DOMAIN: string
    KINDE_AUDIENCE: string
    KINDE_SCOPE: string
    KINDE_CLIENT_ID: string
    KINDE_CLIENT_SECRET: string
    API_BASE_URL: string
    MCP_OBJECT: DurableObjectNamespace<import('./src/index').AuthenticatedMCP>
    AI: Ai
}

declare namespace Cloudflare {
    interface Env {
        NODE_ENV: string
        OAUTH_KV: KVNamespace
        KINDE_DOMAIN: string
        KINDE_AUDIENCE: string
        KINDE_SCOPE: string
        KINDE_CLIENT_ID: string
        KINDE_CLIENT_SECRET: string
        API_BASE_URL: string
        MCP_OBJECT: DurableObjectNamespace<import('./src/index').AuthenticatedMCP>
        AI: Ai
    }
}
